version: "3.9"
networks:
  step-master-dev:
      driver: bridge
services:  
  app: 
    restart: always
    container_name: step-master
    image: chydick/stepmaster    
    ports:
      - "6000:80"
    networks:
      - step-master-dev
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/var/lib/logs  
  udatetitlessm:
    restart: always  
    container_name: update-service
    image: chydick/updatetitlessm
    networks:
      - step-master-dev
    depends_on:
      - mongodb 
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment: # set required env variables to access mongo
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: password

    ports:
      - "27017:27017"
    networks:
      - step-master-dev
    volumes:
      - ./database-data:/data/db
      - ./_scripts/init.js:/docker-entrypoint-initdb.d/mongo-init.js
 


    
    
